const DATA = {
  servers:[{name:'Sarah',pin:'1234'},{name:'Papa',pin:'0000',owner:true},{name:'Serveur',pin:'1111'}],
  tables:[...Array.from({length:12},(_,i)=>`T${i+1}`),'Bar','Terrasse'],
  products:[
    {cat:'Apéritifs',name:'Spritz Aperol',price:9,desc:''},{cat:'Apéritifs',name:'Spritz Saint Germain',price:10,desc:''},{cat:'Apéritifs',name:'Bière Ratz 33cl',price:6,desc:'Blonde / Blanche / Ambrée / Triple'},{cat:'Apéritifs',name:'Fénelon 8cl',price:6.5,desc:''},{cat:'Apéritifs',name:'Kir vin blanc Côtes du Lot 12cl',price:6.5,desc:'Vin blanc, cassis'},{cat:'Apéritifs',name:'Ricard 2cl',price:4.5,desc:''},
    {cat:'Boissons',name:'Jus 25cl',price:4,desc:'Abricot / Ananas / Pomme / ACE / Orange'},{cat:'Boissons',name:'Soda 33cl',price:4,desc:'Coca / Coca Zéro / Orangina / Schweppes / Ice Tea / Perrier / Tonic'},{cat:'Boissons',name:'Abatilles 50cl',price:3,desc:'Plate ou pétillante'},{cat:'Boissons',name:'Abatilles 1L',price:5,desc:'Plate ou pétillante'},{cat:'Boissons',name:'Expresso / Décaféiné',price:2,desc:''},{cat:'Boissons',name:'Double Expresso',price:4,desc:''},{cat:'Boissons',name:'Café viennois',price:3.5,desc:''},{cat:'Boissons',name:'Café au lait',price:3,desc:''},{cat:'Boissons',name:'Thé',price:3,desc:''},
    {cat:'Tapas',name:'Foie Gras de Canard entier 130g',price:32,desc:'Avec toasts'},{cat:'Tapas',name:'Tapenade d’olives noires',price:8,desc:''},{cat:'Tapas',name:'Pimientos à la plancha',price:8,desc:''},{cat:'Tapas',name:'Rillettes pur canard',price:8.5,desc:'Tartinade'},{cat:'Tapas',name:'Foie de canard & Magret de canard',price:9,desc:'Tartinade'},{cat:'Tapas',name:'Cœurs de canard 150g',price:9,desc:''},{cat:'Tapas',name:'Chiffonnade de tête de moine',price:9,desc:''},
    {cat:'Salades',name:'Salade Gourmande Quercynoise',price:24,desc:'Avec tranche de foie gras'},{cat:'Salades',name:'Salade Quercynoise',price:16.5,desc:'Avec gésier de canard'},{cat:'Salades',name:'Chèvre chaud Rocamadour',price:15.5,desc:'Sur toast et magret séché'},{cat:'Salades',name:'Salade de crudités',price:13.5,desc:''},{cat:'Salades',name:'Tomates mozzarella Buffala AOP',price:18.5,desc:'Parmesan, jambon de pays, basilic'},
    {cat:'Plats chauds',name:'Onglet de bœuf 200g à la plancha',price:25,desc:''},{cat:'Plats chauds',name:'Magret de canard entier à la plancha',price:28.5,desc:''},{cat:'Plats chauds',name:'Souris d’agneau',price:27.5,desc:'Écrasé de pommes de terre'},{cat:'Plats chauds',name:'Risotto gambas parmesan',price:18,desc:''},{cat:'Plats chauds',name:'Tataki de thon',price:25,desc:'Tian de légumes, huile de sésame'},{cat:'Plats chauds',name:'Paleron de bœuf confit',price:24,desc:'Carottes vichy, écrasé de pommes de terre'},{cat:'Plats chauds',name:'Cassoulet au confit de canard',price:23.5,desc:'Maison Valette, saucisse de Toulouse'},{cat:'Plats chauds',name:'Côte de Bœuf sur commande',price:82,desc:'Race Charolaise Française 1,2 kg +/-'},
    {cat:'Planches',name:'Tartine chaude',price:9.5,desc:'Tomates, pesto basilic, morbier, jambon de pays'},{cat:'Planches',name:'Grande planche Fromage',price:26,desc:''},{cat:'Planches',name:'Grande planche Charcuterie',price:26,desc:''},{cat:'Planches',name:'Petite planche Fromage',price:14,desc:''},{cat:'Planches',name:'Petite planche Charcuterie',price:14,desc:''},{cat:'Planches',name:'Grande planche Mixte',price:27.5,desc:''},{cat:'Planches',name:'Petite planche Mixte',price:18,desc:''},{cat:'Planches',name:'Planche Gourmande Canard',price:42.5,desc:'Foie gras 130g, magret séché, grattons, saucisse sèche'},
    {cat:'Desserts',name:'Gâteau aux noix',price:7,desc:''},{cat:'Desserts',name:'Crème brûlée maison',price:8.5,desc:''},{cat:'Desserts',name:'Mousse au chocolat maison',price:7,desc:''},{cat:'Desserts',name:'Moelleux au chocolat noir',price:7,desc:''},{cat:'Desserts',name:'Glace 1 boule',price:3.5,desc:'Parfums au choix'},{cat:'Desserts',name:'Glace 2 boules',price:6,desc:'Parfums au choix'},{cat:'Desserts',name:'Glace 3 boules',price:8,desc:'Parfums au choix'},{cat:'Desserts',name:'Supplément chantilly',price:1,desc:''}
  ]
};
let state = JSON.parse(localStorage.getItem('occ_state')||'{}');
state.orders ||= []; state.carts ||= {}; state.currentTable ||= null; state.view ||= 'tables'; state.category ||= 'Tous'; state.search ||= '';
const fmt = n => `${Number(n).toFixed(Number(n)%1?2:0).replace('.',',')}€`;
const save=()=>localStorage.setItem('occ_state',JSON.stringify(state));
const $=s=>document.querySelector(s);
function toast(t){const el=document.createElement('div');el.className='toast';el.textContent=t;document.body.appendChild(el);setTimeout(()=>el.remove(),1700)}
function total(cart){return cart.reduce((s,i)=>s+i.price*i.qty,0)}
function cart(){if(!state.currentTable) return []; return state.carts[state.currentTable] ||= []}
function addItem(item){ if(!state.currentTable){toast('Choisis une table'); state.view='tables'; render(); return} const c=cart(); const key=item.name+'|'+item.price; const ex=c.find(x=>x.key===key); if(ex) ex.qty++; else c.push({...item,key,qty:1}); save(); render(); toast('Ajouté');}
function changeQty(idx,delta){const c=cart(); c[idx].qty+=delta; if(c[idx].qty<=0)c.splice(idx,1); save(); render()}
function tableStatus(t){const has=(state.carts[t]||[]).length; const open=state.orders.find(o=>o.table===t && o.status!=='Payée'); if(open?.status==='Addition')return 'bill'; if(open || has)return 'active'; return ''}
function login(){const pin=$('#pin').value.trim(); const u=DATA.servers.find(s=>s.pin===pin); if(!u) return toast('Code invalide'); state.user=u; state.view='tables'; save(); render();}
function logout(){state.user=null; save(); render()}
function nav(v){state.view=v; save(); render()}
function chooseTable(t){state.currentTable=t; state.view='menu'; save(); render()}
function sendOrder(){const c=cart(); if(!c.length)return toast('Panier vide'); const note=$('#note')?.value||''; state.orders.unshift({id:Date.now(),table:state.currentTable,server:state.user.name,items:c,total:total(c),note,status:'À préparer',time:new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),date:new Date().toLocaleDateString('fr-FR')}); state.carts[state.currentTable]=[]; save(); state.view='orders'; render(); toast('Commande envoyée')}
function setStatus(id,status){const o=state.orders.find(x=>x.id===id); if(o)o.status=status; save(); render()}
function addWine(){const name=$('#wineName').value.trim(); const price=parseFloat($('#winePrice').value.replace(',','.')); const qty=parseInt($('#wineQty').value||'1',10); if(!name||!price)return toast('Nom et prix obligatoires'); for(let i=0;i<qty;i++) addItem({cat:'Vins',name,price,desc:'Saisie libre'});}
function renderLogin(){return `<div class="app login"><div class="brand"><h1>O Clos Chai</h1><p>Manager Service</p></div><div class="card"><h2>Connexion serveur</h2><div class="field"><label>Code PIN</label><input id="pin" inputmode="numeric" type="password" placeholder="1234" onkeydown="if(event.key==='Enter')login()"></div><button class="btn accent" onclick="login()">Se connecter</button><p style="color:var(--muted);font-size:13px">Démo : Sarah 1234 · Papa 0000 · Serveur 1111</p></div></div>`}
function shell(content){return `<div class="app"><div class="topbar"><div class="topline"><div class="title"><h2>${state.view==='tables'?'Salle':state.view==='menu'?'Carte':state.view==='cart'?'Panier':state.view==='orders'?'Commandes':'Patron'}</h2><span>${state.user.name}${state.currentTable?' · '+state.currentTable:''}</span></div><button class="btn small secondary" onclick="logout()">Sortir</button></div></div>${content}</div><div class="footerNav"><button class="navbtn ${state.view==='tables'?'active':''}" onclick="nav('tables')">Tables</button><button class="navbtn ${state.view==='menu'?'active':''}" onclick="nav('menu')">Carte</button><button class="navbtn ${state.view==='cart'?'active':''}" onclick="nav('cart')">Panier</button><button class="navbtn ${state.view==='orders'?'active':''}" onclick="nav('orders')">Commandes</button><button class="navbtn ${state.view==='boss'?'active':''}" onclick="nav('boss')">Patron</button></div>`}
function renderTables(){return `<div class="card"><b>Légende</b><p><span class="pill">Libre</span> <span class="pill">En cours</span> <span class="pill">Addition</span></p></div><div class="grid">${DATA.tables.map(t=>`<button class="table" onclick="chooseTable('${t}')"><i class="dot ${tableStatus(t)}"></i>${t}<span>${(state.carts[t]||[]).length?fmt(total(state.carts[t])):'ouvrir'}</span></button>`).join('')}</div>`}
function renderMenu(){const cats=['Tous','Vins',...new Set(DATA.products.map(p=>p.cat))]; const q=state.search.toLowerCase(); const items=DATA.products.filter(p=>(state.category==='Tous'||p.cat===state.category)&&(!q||p.name.toLowerCase().includes(q)||p.desc.toLowerCase().includes(q))); return `<div class="tabs">${cats.map(c=>`<button class="tab ${state.category===c?'active':''}" onclick="state.category='${c}';save();render()">${c}</button>`).join('')}</div>${state.category==='Vins'?`<div class="wineBox"><h3>🍷 Vin en saisie libre</h3><div class="field"><label>Nom du vin</label><input id="wineName" placeholder="Ex : Château du Cèdre, verre Malbec..."></div><div class="field"><label>Prix</label><input id="winePrice" inputmode="decimal" placeholder="Ex : 8 ou 42"></div><div class="field"><label>Quantité</label><input id="wineQty" inputmode="numeric" value="1"></div><button class="btn" onclick="addWine()">Ajouter le vin</button></div>`:''}<div class="search"><input placeholder="Rechercher un produit" value="${state.search}" oninput="state.search=this.value;save();render()"></div>${items.map(p=>`<div class="menuItem"><div><b>${p.name}</b><small>${p.cat}${p.desc?' · '+p.desc:''}</small></div><div class="qty"><span class="price">${fmt(p.price)}</span><button class="round" onclick='addItem(${JSON.stringify(p)})'>+</button></div></div>`).join('')||'<div class="empty">Aucun produit</div>'}<CartBar/>`}
function renderCart(){const c=cart(); return `<div class="card"><h3>${state.currentTable||'Aucune table'}</h3>${c.length?c.map((i,idx)=>`<div class="cartLine"><div><b>${i.qty} × ${i.name}</b><small>${fmt(i.price)} unité</small></div><div class="qty"><button class="round" onclick="changeQty(${idx},-1)">−</button><button class="round" onclick="changeQty(${idx},1)">+</button></div></div>`).join(''):'<div class="empty">Panier vide</div>'}<div class="field"><label>Note cuisine/bar</label><textarea id="note" placeholder="Ex : sans sauce, envoyer en terrasse, vin à carafer..."></textarea></div><h2>Total ${fmt(total(c))}</h2><button class="btn accent" onclick="sendOrder()">Envoyer la commande</button></div>`}
function renderOrders(){return state.orders.length?state.orders.map(o=>`<div class="orderCard"><div class="orderHead"><div><b>#${String(o.id).slice(-5)} · ${o.table}</b><br><small>${o.server} · ${o.time} · ${o.date}</small></div><span class="status ${o.status==='Payée'?'done':o.status==='Addition'?'bill':'pending'}">${o.status}</span></div><p>${o.items.map(i=>`${i.qty}× ${i.name}`).join('<br>')}</p>${o.note?`<small>Note : ${o.note}</small>`:''}<h3>${fmt(o.total)}</h3><div class="tabs"><button class="tab" onclick="setStatus(${o.id},'À préparer')">À préparer</button><button class="tab" onclick="setStatus(${o.id},'Servie')">Servie</button><button class="tab" onclick="setStatus(${o.id},'Addition')">Addition</button><button class="tab" onclick="setStatus(${o.id},'Payée')">Payée</button></div></div>`).join(''):'<div class="empty">Aucune commande</div>'}
function renderBoss(){const day=state.orders; const ca=day.filter(o=>o.status==='Payée').reduce((s,o)=>s+o.total,0); const open=day.filter(o=>o.status!=='Payée').reduce((s,o)=>s+o.total,0); return `<div class="kpi"><div class="card"><span>CA encaissé</span><br><b>${fmt(ca)}</b></div><div class="card"><span>En cours</span><br><b>${fmt(open)}</b></div></div><div class="card"><h3>Vue caisse</h3>${renderOrders()}</div>`}
function CartBar(){const c=cart();return `<div class="cartbar"><div class="cartinner"><div class="totalbox">${c.length} art.<br>${fmt(total(c))}</div><button class="btn" onclick="nav('cart')">Voir panier</button></div></div>`}
function render(){ if(!state.user){document.getElementById('app').innerHTML=renderLogin();return} const views={tables:renderTables,menu:renderMenu,cart:renderCart,orders:renderOrders,boss:renderBoss}; document.getElementById('app').innerHTML=shell(views[state.view]())}
render();
